### ISSUE TITLE
fix: Ambiguous JSON types on Transaction Endpoint

### ISSUE THREAD

**Issue by nijuyonkadesu** [niyasrad/CelestiDesk-BE#19]
## Bug Description
The postman response is different from how it is defined in `src/models`. It is confusing.  Which one is the correct one?

## Steps to Reproduce
1. Call the `\transaction\history` endpoint from `TEAM_LEAD` or from `MANAGER` role.

## Expected Response
![image](https://github.com/niyasrad/CelestiDesk-BE/assets/85601344/3f239217-cd91-4799-bfcc-498a227ea08e)

## Actual Response
![image](https://github.com/niyasrad/CelestiDesk-BE/assets/85601344/0c479dfe-66a6-42ec-92af-41af4aa4efa0)

### Case 1:
If, the actual response is the right one, it would be better to have the following fields in addion:
![image](https://github.com/niyasrad/CelestiDesk-BE/assets/85601344/d5927f75-bb20-494e-9efc-bb0064ffc0ff)
![image](https://github.com/niyasrad/CelestiDesk-BE/assets/85601344/0384cfce-4367-4064-aedc-8aea45c3e933)

### Case 2:
If, the expected Response is the right one, then, I believe, it has more data than what is actually required. The response feels like "you've literally made SQL Joins in NoSQL" lmao 😁

**Comment by niyasrad** [comment]
Thank you for finding the issue~!

Essentially, during testing, I had to remove the requests directly from the backend, this doesn't resolve the history of transactions though, that's why the relation caused a `null` value to be returned. I will work on this!

And please open a separate issue on what data you want, and how you want the data to be clean.
